Increase portability for json_ls, minor fixes

diff --git a/bin/json_ls b/bin/json_ls
--- a/bin/json_ls
+++ b/bin/json_ls
@@ -8,6 +8,8 @@ include() { . "${1}" || exit 1; }
 
 include ../lib/jsonprint.sh
 
+json_require stat
+
 shopt -s dotglob nullglob
 
 # Figure out which checksum method is available, start with sha256sum
@@ -30,43 +32,68 @@ elif command -v cksum > /dev/null 2>&1; then
     get_file_checksum() { cksum "${1:?No target specified}" | awk '{print $1}'; }
 fi
 
-# If we get to this point, let's start building our JSON output
-json_open
-  json_arr_open "${PWD}"
-    json_obj_open
-      # We keep a track of how many files are here and how many times we loop
-      # This is so that we know not to emit a trailing comma on the last object
-      loop_iter=0
-      set -- *
-      fsobj_count="${#}"
-      for fsobj in *; do
-        fsobj_type="$(stat -c "%F" "${fsobj}")"
-        fsobj_link="$(stat -c "%N" "${fsobj}" | tr -d "'")"
-        fsobj_name="$(stat -c "%n" "${fsobj}" | json_str_escape)"
-        
-        # Read in a formatted sequence from 'stat' and assign to our vars
-        while read -r fsobj_uid fsobj_gid fsobj_mode fsobj_size fsobj_mtime fsobj_atime fsobj_birth; do
-          # Place those vars into our JSON structure
-          json_str fileName "${fsobj_name}"
-          json_str_append fileOwner "${fsobj_uid}"
-          json_str_append fileGroup "${fsobj_gid}"
-          json_num_append fileMode "${fsobj_mode}"
-          json_num_append sizeBytes "${fsobj_size}"
-          json_num_append fileModified "${fsobj_mtime}"
-          json_num_append fileAccessed "${fsobj_atime}"
-          (( fsobj_birth > 0 )) && json_num_append fileCreated "${fsobj_birth}"
-          json_str_append fileType "${fsobj_type}"
-          json_str_append dereference "${fsobj_link}"
-          json_str_append checksum "$(get_file_checksum "${fsobj}")"
-        done < <(stat -c "%U %G %a %s %Y %X %W" "${fsobj}")
-        # As above, track our loop count so that we can appropriately
-        # emit the last object without a trailing comma
-        (( loop_iter++ ))
-      if (( loop_iter < fsobj_count )); then
-        json_obj_append
-      else
-        json_obj_close
-      fi
-    done
-  json_arr_close
-json_close
+get_stat_output() {
+  stat -c "%U %G %a %s %Y %X %W" "${1:?No target specified}" 2>/dev/null ||
+    stat -f "%Su %Sg %Op %z %m %a %B" "${1}"
+}
+
+produce_json_output() {
+  # If we get to this point, let's start building our JSON output
+  json_open
+    json_arr_open "${PWD}"
+      json_obj_open
+        # We keep a track of how many files are here and how many times we loop
+        # This is so that we know not to emit a trailing comma on the last object
+        loop_iter=0
+        set -- *
+        fsobj_count="${#}"
+        for fsobj in *; do
+          fsobj_type="$(stat -c "%F" "${fsobj}" 2>/dev/null || stat -f "%T")"
+          fsobj_link="$( (stat -c "%N" "${fsobj}" 2>/dev/null || stat -f "%Y") | tr -d "'")"
+          fsobj_name="$( (stat -c "%n" "${fsobj}" 2>/dev/null || stat -f "%N") | json_str_escape)"
+          
+          # Read in a formatted sequence from 'stat' and assign to our vars
+          while read -r fsobj_uid fsobj_gid fsobj_mode fsobj_size fsobj_mtime fsobj_atime fsobj_birth; do
+            #Cleanup fsobj_mode just in case we've had a BSD style output
+            fsobj_mode="${fsobj_mode#"${fsobj_mode%???}"}"
+            # Place those vars into our JSON structure
+            json_str fileName "${fsobj_name}"
+            json_str_append fileOwner "${fsobj_uid}"
+            json_str_append fileGroup "${fsobj_gid}"
+            json_num_append fileMode "${fsobj_mode}"
+            json_num_append sizeBytes "${fsobj_size}"
+            json_num_append fileModified "${fsobj_mtime}"
+            json_num_append fileAccessed "${fsobj_atime}"
+            (( fsobj_birth > 0 )) && json_num_append fileCreated "${fsobj_birth}"
+            json_str_append fileType "${fsobj_type}"
+            json_str_append dereference "${fsobj_link}"
+            json_str_append checksum "$(get_file_checksum "${fsobj}")"
+          done < <(get_stat_output "${fsobj}")
+          # As above, track our loop count so that we can appropriately
+          # emit the last object without a trailing comma
+          (( loop_iter++ ))
+        if (( loop_iter < fsobj_count )); then
+          json_obj_append
+        else
+          json_obj_close
+        fi
+      done
+    json_arr_close
+  json_close
+}
+
+# Ok, let's start accepting some basic args.  Namely a target.
+case "${1}" in
+  ('') produce_json_output ;;
+  (*)
+    fsobj="${1}"
+    if [ -d "${fsobj}" ]; then
+      (
+        cd "${fsobj}" || exit 1
+        produce_json_output
+      )
+    elif [ -r "${fsobj}" ]; then
+      :
+    fi
+  ;;
+esac
